### ISSUE TITLE
Syllabus

### ISSUE THREAD

**Issue by gp1d** [ahmadazim/STAT117#1]
I would like to work on the syllabus over the weekend. Please pint me to the right place.

**Comment by ahmadazim** [comment]
The about.qmd file is where the syllabus information is (perhaps we can change this file name actually). I was working on the gh-pages branch earlier but the main branch should now be up to date!

**Comment by ahmadazim** [comment]
If it is helpful, I was following instructions from this page: https://quarto.org/docs/publishing/github-pages.html
Once you make changes locally, simply running `quarto publish gh-pages` should automatically launch the corresponding GitHub action. Then pushing to the main branch `git push -u origin main` will update the main repo branch.

**Comment by gp1d** [comment]
thanks. that's really useful to know ---I was thinking of doing these from RStudio, but command line could definitely come handy. do you think we should have separate branches, and pull requests, or keep it simpler?

**Comment by ahmadazim** [comment]
Anything works for me! Perhaps if it is just a quick / simple change, we can just push to main and update the website, but if it's something we would like the other to review, we can open a pull request?

**Comment by gp1d** [comment]
actually it seems that RStudio already creates a separate branch and has pull / merge functionality.

**Comment by gp1d** [comment]
> Anything works for me! Perhaps if it is just a quick / simple change, we can just push to main and update the website, but if it's something we would like the other to review, we can open a pull request?

sounds good
