### ISSUE TITLE
lectures 1 and 2

### ISSUE THREAD

**Issue by gp1d** [ahmadazim/STAT117#2]
I would like to spend some time this morning editing lectures 1 and 2. can you please push any changes you may have made this weekend?

**Comment by gp1d** [comment]
I just pushed L1, as I was running out of time.

**Comment by gp1d** [comment]
please do not make any changes to lecture 2 between now and Thursday.

**Comment by ahmadazim** [comment]
will do!

**Comment by ahmadazim** [comment]
Also, would you like me to "hide" all lectures beyond lectures 1 and 2 for now?

**Comment by gp1d** [comment]
yes, this might be a good idea for now, we can work out a general approach when we meet today.

**Comment by gp1d** [comment]
can you please commit and push the versions of lecture 3 and 4 with the questions you showed me yesterday? I need to post L3 today at the latest.

**Comment by ahmadazim** [comment]
Hi Giovanni, working on it now. Should be pushed in the next 30 min!
