### ISSUE TITLE
Figure Size

### ISSUE THREAD

**Issue by gp1d** [ahmadazim/STAT117#3]
To control the figure size when rendering a Quarto document in HTML, you can use the fig-width and fig-height options in the document header. These options allow you to specify the default size for computational figures. For example, you can change the display size by adding the width and height attributes to the figure, such as {width=80%} or {width=4in}. If only the width is specified, then the height is calculated automatically. Additionally, you can use the out-width parameter to scale the image if the generated image is not big enough to fill the full screen

**Comment by gp1d** [comment]
never mind, this is for computational figures

**Comment by gp1d** [comment]
this is more promising. https://github.com/quarto-dev/quarto-cli/discussions/6670

**Comment by gp1d** [comment]
I'm now trying to implement the .lightbox option but having a hard time. do you have a few minutes around 11 to help me troubleshoot and get on the same page about a couple of urgent things?

**Comment by ahmadazim** [comment]
I've been trying to figure this out but haven't successfully implemented it. I will keep you posted on if I figure it out before lecture.

**Comment by gp1d** [comment]
I resorted to manually setting the seize of each figure. not too onerous consider there are very few after L2 and L3
