### ISSUE TITLE
GP authentication

### ISSUE THREAD

**Issue by gp1d** [ahmadazim/STAT117#5]
I can get in through the browser but terminal and RStudio are no longer able to talk to the repo. did you change any of the security settings?

**Comment by ahmadazim** [comment]
Nothing should have changed, the security setting are unmodified. I can still access the repo from my terminal. Perhaps try pulling again?

**Comment by gp1d** [comment]
I think I solved it. not sure what caused it but I uninstalled the desktop app, reconfigured all the ssh stuff from scratch, and cloned the repo again.
